# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questtion_text',
            new_name='question_text',
        ),
    ]
